{
 "title": "LLM Router Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total # of Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(num_requests)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per Policy",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(policy) (requests_per_policy)",
     "legendFormat": "{{policy}}"
    }
   ]
  },
  {
   "title": "Tokens per Classification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(llm_name) (llm_token_usage)",
     "legendFormat": "{{llm_name}}"
    }
   ]
  },
  {
   "title": "Router Overhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(model_selection_time_seconds_sum[$__rate_interval])",
     "legendFormat": "Latency (ms)"
    }
   ]
  }
 ]
}